---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 2048

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  network:
    - ['private_network', {ip: '192.168.33.33'}]

suites:
- name: default
  run_list: ["recipe[minecraft-chef-server]"]
  attributes: {}
